
services:

  django:
    image: smart-wash-backend
    container_name: smart-wash-backend
    build: .
    tty: true
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file: .environment
    volumes:
      - .:/code
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgis/postgis
    container_name: smart-wash-postgres
    ports:
      - 5432:5432
    volumes:
      - ./storage/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres



networks:
  host:
    name: core
