# Generated by Django 5.0.6 on 2024-05-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarWash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.CharField(max_length=255, verbose_name='Ссылка на фото')),
                ('plate_number', models.CharField(blank=True, max_length=10, verbose_name='Номерной знак')),
                ('detected_at', models.DateTimeField(auto_now=True, verbose_name='Время заезда авто')),
                ('recognized_at', models.DateTimeField(null=True, verbose_name='Время распознавания номерного знака')),
                ('out_at', models.DateTimeField(null=True, verbose_name='Время выезда авто')),
            ],
        ),
    ]
